# Generated by Django 5.1.4 on 2025-01-07 22:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exercises/images/"
                    ),
                ),
                ("multiple_choice", models.BooleanField(default=False)),
                ("choice1", models.CharField(blank=True, max_length=200, null=True)),
                ("choice2", models.CharField(blank=True, max_length=200, null=True)),
                ("choice3", models.CharField(blank=True, max_length=200, null=True)),
                ("choice4", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lessons/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="lessons/videos/"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="lessons/pdfs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=25, samples=None
                    ),
                ),
            ],
        ),
    ]
